# Generated by Django 3.1.2 on 2020-10-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testWithinTenDays', models.BooleanField()),
                ('beingtoHotSpot', models.BooleanField()),
                ('age', models.IntegerField()),
                ('pregnant', models.BooleanField()),
                ('copd', models.BooleanField()),
                ('testproof', models.FileField(blank=True, upload_to='test')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('color', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('addressLine1', models.TextField()),
                ('addressLine2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNum', models.IntegerField()),
                ('checkInDt', models.DateField()),
                ('checkInTm', models.TimeField()),
                ('departDt', models.DateField()),
                ('departTm', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HackPanther.user')),
            ],
        ),
    ]
